apiVersion: v1
kind: Service
metadata:
  labels:
    name: sonar
  name: sonar
  namespace: sonarqube
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9000
  selector:
    name: sonarqube