apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-postgre-pvc # modify
  namespace: sonarqube # modify
  labels:
    type: postgre
spec:
  storageClassName: postgre
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
