apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        securityContext:
          runAsUser: 0
          privileged: true
        ports:
          - name: http-port
            containerPort: 8080
        volumeMounts:
          - name: jenkins-docker-sock
            mountPath: /var/run/docker.sock
          - name: jenkins-docker
            mountPath: /usr/bin/docker
          - name: jenkins-home
            mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: jenkins-docker
          hostPath:
            path: /usr/bin/docker
        - name: jenkins-home
          hostPath:
            path: /root/k8s-cookalone/jenkins/jenkins_home